version: '3.9'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
  test_client:
    build: .
    command: python3 src/main.py
    ports:
      - "8085:8085"
    depends_on:
      - db