apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
  labels:
    app: mssql
spec:
  serviceName: mssql-server
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2017-latest
          args:
            - /bin/bash
            - -c
            - |
              /opt/mssql/bin/sqlservr & sleep 30 && /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'yourStrong(!)Password' -i /sql/init.sql && tail -f /dev/null
          imagePullPolicy: Always
          ports:
          - containerPort: 1433
          resources:
            limits:
              cpu: "500m"
              memory: 1Gi
            requests:
              cpu: "500m"
              memory: 1Gi
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              value: "yourStrong(!)Password"
            - name: MSSQL_PID
              value: "Developer"
          volumeMounts:
            - name: init
              mountPath: /sql
            - name: mssql-data
              mountPath: /var/opt/mssql
            - name: data
              mountPath: /data
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'yourStrong(!)Password' -Q 'SELECT 1' || exit 1
            initialDelaySeconds: 30
            timeoutSeconds: 5
      volumes:
        - name: "data"
          hostPath:
            path: "/infrBigDataLab8/data"
        - name: "init"
          hostPath:
            path: "/infrBigDataLab8/sql"
  volumeClaimTemplates:
  - metadata:
      name: mssql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: fast
      resources:
        requests:
          storage: 1Gi
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast
provisioner: k8s.io/minikube-hostpath
parameters:
  type: pd-ssd