apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: kmeans-spark
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  image: "kirrog76/infr_big_data6:latest"
  imagePullPolicy: Always
  mainApplicationFile: "local:///app/scripts/run.py"
  sparkVersion: "3.5.1"
  deps:
    jars:
      - local:///app/jars/mssql-jdbc-12.6.1.jre11.jar
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "4g"
    labels:
      version: 3.4.1
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: "16g"
    labels:
      version: 3.4.1